ofborg/infrastructure

- nixops/modules/monitoring.nix
Makes received alert's source links useful.
> Specify the external URL for prometheus alerts

- nixops/modules/monitoring.nix
The 4h prediction triggers semi-regularly on the aarch64 builder.
> alertmanager: reduce filesystem free prediction to 2h

- nixops/modules/monitoring.nix
The aarch builder is used by the ofborg infrastructure, but if it runs
out of diskspace enough to stall builds there's another alert that will
still trigger.
> remove the aarch community builder from filesystem alerts

- nixops/network.nix
RIP.
---
Else, deploys will fail.
I didn't touch any of the other Hetzner-related files. Provided a list of files to delete/drop references to Hetzner from, I'd be happy to deal with that prior to merging.
> Drop Hetzner host

- nixops/modules/site.nix
ofborg no longer makes a distinction between known users and unknown
users; all PRs get built.
The only distinction remaining is between trusted and untrusted users:
trusted users will have their builds be built on darwin, in addition to
the x86_64-linux and aarch64-linux builders everyone gets.
---
Depends on https://github.com/NixOS/ofborg/pull/482.
> Remove {extra-,}known-users

- nixops/network.nix
No more having to copy ~20 lines for every new evaluator that we need to
add. Just change `numMachines 6` to `numMachines N`, where N is the
desired number of total evaluators.
> nixops: generalize evaluator setup

- nixops/modules/monitoring.nix
- nixops/modules/rabbitmq/default.nix
This exposes some of the same data as the queue-monitor and a bunch
more. Once prometheus has some historical data that can probably be
replaced.
> enable and configure rabbitmq-exporter

- nixops/network.nix
Prior to this change, one would need to commit (via PR or directly) to
change the number of hosts. Now, one just needs to set
`OFBORG_PACKET_HOSTS` to the number of desired hosts when deploying via
Buildkite. If `OFBORG_PACKET_HOSTS` is unspecified, it will default to 3
hosts.
> variable amount of hosts without committing

- build/build.sh
This will release the extra evaluators whenever we scale the amount of
evaluators down.
We exclude core-0 because it would be really nice to not delete that
host...
---
`--include core-0` on the second instance so we don't deploy twice to the evaluators we do keep.
> kill obsolete machines

- ci/terraform-import.yml
This ensures we can deploy even if we are low on space.
No blocking, but still `concurrency: 1`.
> ci: collect garbage before dry activation

- ci/collect-garbage.sh
- ci/terraform-import.yml
- shell.nix
coreutils is necessary for `wc -l`.
> ci: collect garbage per machine

- nix/sources.json
- nixops/modules/rabbitmq/default.nix
Since the rabbitmq_exporter was updated to 1.0.0-RC7.1, the cloudAMQP
root ceritifcate should be supported now.
> rabbitmq: remove SKIPVERIFY

- shell.nix
This is disallowed as of
https://github.com/NixOS/nixpkgs/commit/863706ef307a4fa62370b7ee0db85f10a422e880.
> shell.nix: remove goPackagePath from buildGoModule's

- .gitignore
- enter-env.sh
The script writes them out again, so let's remove them after we're done
in the environment.
> enter-env: remove secrets

- ci/terraform-deploy.yml
- ci/terraform-import.yml
Otherwise, it would use the old targets. A new run will be automatically
scheduled after the HEAD is pushed to, which will then incorporate the new
targets.
> terraform-import: deploy only if targets unchanged

- terraform/base/amqp.tf
For posterity:
$ ./enter-env.sh
$ cd terraform/base
$ $EDITOR amqp.tf # and fix the typo
$ terraform init
$ terraform state mv cloudamqp_plugin.instance-plugin-web_stop cloudamqp_plugin.instance-plugin-web_stomp
$ terraform plan
$ git add amqp.tf && git commit -v
$ git push vaultpush
---
https://github.com/ofborg/infrastructure/commit/72beb8e690a91648d3a523dacb7d3e7668c34477#r46973864
> amqp.tf: web_stop -> web_stomp

- nixops/modules/ofborg/evaluator.nix
Work around the rare appearance of
error: all build users are currently in use; consider creating additional users and adding them to the 'nixbld' group
> ofborg/evaluator: 128 build users

- nixops/modules/ofborg/evaluator.nix
This way we don't have to manually intervene by starting a deploy,
just to run the GC steps.
> ofborg/evaluator: automatic gc once a week

- nixops/modules/macos_vm/guest-catalina/darwin-configuration.nix
Otherwise, darwin-rebuild will not be found in subsequent sessions.
> darwin-configuration: configure zsh

- nixops/modules/monitoring.nix
It's not good to have alerts for things that aren't actually severe, so
let's ignore this queue.
> Ignore lowprior queues

- shell.nix
They recently switched from using the experimental nix(1) interface back
to the legacy nix-instantiate and friends. We can't currently deploy
because of issues caused by these experimental features, such as:
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
Error while running `nix eval ..`: exit status 1
> Bump morph

- nixops/modules/monitoring.nix
Otherwise, after a recent upgrade to Grafana, it was no longer possible
to log in.
ref: https://community.grafana.com/t/origin-not-allowed-messages-after-upgrade-to-8-3-6/60550/
> modules/monitoring: enable recommendedProxySettings

- buildkite.yml
- ci/collect-garbage.sh
- ci/terraform-base-apply.yml
- ci/terraform-deploy.yml
- ci/terraform-import.yml
- ci/terraform-rabbitmq-apply.yml
- ci/terraform-rabbitmq-plan.yml
The buildkite user doesn't look up root's channels anymore, so we need to make sure the buildkite user has channels setup. Otherwise, old versions of bash will be problematic (i.e. the one we have in Amazon Linux).
> Add and update nix-channel in buildkite

- flake.lock
- nix/sources.json
- nixops/modules/ofborg/default.nix
Flake lock file updates:
• Updated input 'darwin':
'github:LnL7/nix-darwin/f6648ca0698d1611d7eadfa72b122252b833f86c' (2022-10-26)
→ 'github:LnL7/nix-darwin/87b9d090ad39b25b2400029c64825fc2a8868943' (2023-01-09)
• Updated input 'nixpkgs':
'github:nixos/nixpkgs/7ba7b4599367c07f2f5d1e26151b68a71a1336b2' (2022-12-22)
→ 'github:nixos/nixpkgs/1e383aada51b416c6c27d4884d2e258df201bc11' (2023-03-08)
• Updated input 'ofborg':
'github:NixOS/ofborg/6d5ad2f34bad811885dffeaac33d5a3546848123' (2022-12-22)
→ 'github:NixOS/ofborg/cf2c6712bd7342406e799110e7cd465aa250cdca' (2023-02-14)
> Update Nixpkgs, use Nix 2.13
